name: flutter_reactive_value
description: Simple reactive state management for Flutter.
version: 1.0.3
homepage: https://github.com/lukehutch/flutter_reactive_value

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
